### PR TITLE
add documentation about multiple instance

### PR DESCRIPTION
**Pull request by tbntdima**
Add info about multiple instances of the Slider on the same page

### CODE REVIEW

**Comment by tbntdima** [comment]
@michelecocuccio unfortunately I meant context provider.
I’ve tried SRLWrapper it worked locally, but on production (probably because it waits for images to be loaded) there were lags on next prev buttons and autoplay.

**Comment by michelecocuccio** [comment]
@tbntdima yes that's correct. If you want multiple light-boxes on the same page you need to wrap them in different providers. Sorry, I misunderstood your documentation which is indeed correct :)

**Comment by tbntdima** [comment]
@michelecocuccio, nice, happy to contribute 🙂

**Comment by tbntdima** [comment]
@michelecocuccio done!

**Pull request merged**
